apiVersion: batch/v1
kind: Job
metadata:
  name: 224-7
spec:
  template:
    metadata:
    spec:
      restartPolicy: Never
      containers:
      - name: main-container
        image: perl
        imagePullPolicy: Always
        command:
        - perl
        - -Mbignum=bpi
        - -wle
        - print bpi(2000)
